apiVersion: ansible.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  annotations:
    ansible.crossplane.io/runPolicy: ObserveAndDelete
  name: gcpbucket
spec:
  forProvider:
    # AnsibleRun default to using a remote source - like ansibleRun-remote.yaml.
    # For simple cases you can use an inline source to specify the content of
    # playbook.yaml as opaque, inline yaml.
    # playbook source : https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_storage_bucket_module.html#examples
    playbookInline: |
      ---
      - hosts: localhost
        tasks:
          - name: create a gcp bucket
            google.cloud.gcp_storage_bucket:
              name: ansible-storage-module
              project: test-project
              auth_kind: serviceaccount
              service_account_file: gcp-credentials.json
              state: present
            when: ansible_provider_meta.gcpbucket.state == 'present'
  providerConfigRef:
    name: default