apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: gcp-credentials
type: Opaque
data:
  credentials: BASE64ENCODED_PROVIDER_CREDS
---
apiVersion: ansible.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  # Note that unlike most provider configs this one supports an array of
  # credentials. This is because each Ansible playbook uses a single
  # Crossplane provider config, but could use multiple providers each
  # with their own credentials.
  credentials:
    - filename: gcp-credentials.json
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: gcp-credentials
        key: credentials
  requirements: |
    ---
    collections:
      - name: google.cloud
        source: https://galaxy.ansible.com
        version: "1.0.2"
